# Generated by Django 3.1.2 on 2020-10-17 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("donation_venue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icd_code", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="auth.user",
                    ),
                ),
                (
                    "last_symptom_date",
                    models.DateField(verbose_name="covid_last_symptom_date"),
                ),
                ("blood_group", models.CharField(max_length=3)),
                ("test_report", models.TextField(blank=True)),
                ("height", models.PositiveSmallIntegerField()),
                ("weight", models.PositiveSmallIntegerField()),
                ("diseases", models.ManyToManyField(to="donor.Disease")),
            ],
        ),
        migrations.CreateModel(
            name="DonorRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now=True)),
                ("did_donation", models.BooleanField(default=False)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="donor.donor"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donation_venue.donationvenue",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="donor",
            name="venues",
            field=models.ManyToManyField(
                through="donor.DonorRegistration", to="donation_venue.DonationVenue"
            ),
        ),
    ]
