# Generated by Django 3.1.2 on 2020-10-17 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donation_venue", "0001_initial"),
        ("user", "0001_initial"),
        ("donor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="user.user",
                    ),
                ),
                (
                    "last_symptom_date",
                    models.DateField(verbose_name="covid_last_symptom_date"),
                ),
                ("blood_group", models.CharField(max_length=3)),
                ("test_report", models.TextField(blank=True)),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="height_in_feet"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="weight_in_kg"
                    ),
                ),
                ("diseases", models.ManyToManyField(to="donor.Disease")),
            ],
        ),
        migrations.CreateModel(
            name="DonorRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now=True)),
                ("did_donation", models.BooleanField(default=False)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="donor.donor"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donation_venue.donationvenue",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="donor",
            name="venues",
            field=models.ManyToManyField(
                through="donor.DonorRegistration", to="donation_venue.DonationVenue"
            ),
        ),
        migrations.AddConstraint(
            model_name="donor",
            constraint=models.CheckConstraint(
                check=models.Q(height__gt=0.01), name="height_gt_0.01"
            ),
        ),
        migrations.AddConstraint(
            model_name="donor",
            constraint=models.CheckConstraint(
                check=models.Q(weight__gt=0.01), name="weight_gt_0.01"
            ),
        ),
    ]
