# Generated by Django 3.1.2 on 2020-10-17 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="height",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="height_in_feet",
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="weight_in_kg",
            ),
        ),
    ]
