# Generated by Django 3.1.2 on 2020-10-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20201017_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='height_in_feet'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='weight_in_kg'),
        ),
        migrations.AddConstraint(
            model_name='donor',
            constraint=models.CheckConstraint(check=models.Q(height__gt=0.01), name='height_gt_0.01'),
        ),
        migrations.AddConstraint(
            model_name='donor',
            constraint=models.CheckConstraint(check=models.Q(weight__gt=0.01), name='weight_gt_0.01'),
        ),
    ]
