# Generated by Django 3.1.2 on 2020-11-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0003_auto_20201017_2250"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donorregistration",
            options={"verbose_name": "Donor Registration"},
        ),
        migrations.RenameField(
            model_name="donor",
            old_name="id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="donorregistration",
            name="did_donation",
            field=models.BooleanField(
                default=False, verbose_name="Check if the donor donated on the venue"
            ),
        ),
    ]
