# Generated by Django 3.1.3 on 2020-11-07 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0004_auto_20201107_2231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="height",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0.02)],
                verbose_name="height (in feet)",
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0.02)],
                verbose_name="weight (in kg)",
            ),
        ),
    ]
