# Generated by Django 3.1.3 on 2020-11-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0005_auto_20201108_0004"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="donor",
            name="height_gt_0.01",
        ),
        migrations.RemoveConstraint(
            model_name="donor",
            name="weight_gt_0.01",
        ),
        migrations.AddConstraint(
            model_name="donor",
            constraint=models.CheckConstraint(
                check=models.Q(height__gt=0.01), name="donor_height_gt_0.01"
            ),
        ),
        migrations.AddConstraint(
            model_name="donor",
            constraint=models.CheckConstraint(
                check=models.Q(weight__gt=0.01), name="donor_weight_gt_0.01"
            ),
        ),
    ]
