# Generated by Django 3.1.3 on 2020-11-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0007_auto_20201108_1426"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="diseases",
            field=models.ManyToManyField(blank=True, null=True, to="donor.Disease"),
        ),
    ]
