# Generated by Django 3.1.3 on 2020-11-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_auto_20201108_1435'),
        ('donor', '0008_auto_20201108_1428'),
    ]

    operations = [
    ]
