# Generated by Django 3.1.4 on 2020-12-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donation_venue", "0005_auto_20201108_1158"),
        ("donor", "0009_merge_20201108_1443"),
    ]

    operations = []
