# Generated by Django 3.1.4 on 2020-12-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_venue", "0005_auto_20201108_1158"),
        ("donor", "0009_merge_20201108_1443"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="test_report",
            field=models.ImageField(
                blank=True, upload_to="test_reports/", verbose_name="Test Report"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="donorregistration",
            unique_together={("donor", "venue")},
        ),
    ]
