# Generated by Django 3.1.4 on 2020-12-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0010_auto_20201216_1552"),
        ("donor", "0010_auto_20201216_1646"),
    ]

    operations = []
