# Generated by Django 3.1.2 on 2020-11-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_venue", "0002_auto_20201017_2250"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="donationvenue",
            constraint=models.UniqueConstraint(
                fields=("name", "address"), name="unique_name_address"
            ),
        ),
    ]
