# Generated by Django 3.1.3 on 2020-11-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_venue", "0003_auto_20201107_2231"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="donationvenue",
            name="unique_name_address",
        ),
        migrations.AddConstraint(
            model_name="donationvenue",
            constraint=models.UniqueConstraint(
                fields=("name", "address"), name="donationvenue_unique_name_address"
            ),
        ),
    ]
