# Generated by Django 3.1.3 on 2020-11-08 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_venue", "0004_auto_20201108_1146"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationvenue",
            name="phone_number",
            field=models.PositiveBigIntegerField(
                validators=[django.core.validators.MinValueValidator(100)],
                verbose_name="Phone Number",
            ),
        ),
        migrations.AddConstraint(
            model_name="donationvenue",
            constraint=models.CheckConstraint(
                check=models.Q(phone_number__gte=100),
                name="donationvenue_phone_number_gte_100",
            ),
        ),
    ]
