# Generated by Django 3.1.2 on 2020-10-17 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventtype",
            options={"verbose_name": "Event Type"},
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="event.eventtype",
                verbose_name="Event Type",
            ),
        ),
    ]
