# Generated by Django 3.1.2 on 2020-11-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_auto_20201017_2250"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
