# Generated by Django 3.1.2 on 2020-11-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_auto_20201107_2211"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="name",
            field=models.CharField(default="Rakta Daan, Jiwan Daan", max_length=100),
            preserve_default=False,
        ),
    ]
