# Generated by Django 3.1.4 on 2020-12-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_event_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="details",
            field=models.TextField(default=""),
        ),
    ]
