"""Do not add volunteer_id inside skill table

Revision ID: 21fd69d0156a
Revises: 730ca38534b2
Create Date: 2020-10-11 20:14:12.125478

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "21fd69d0156a"
down_revision = "730ca38534b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("skill_ibfk_1", "skill", type_="foreignkey")
    op.drop_column("skill", "volunteer_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "skill",
        sa.Column(
            "volunteer_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "skill_ibfk_1", "skill", "volunteer", ["volunteer_id"], ["id"]
    )
    # ### end Alembic commands ###
