"""Now user can have gender and dob

Revision ID: e5f90cb63967
Revises: 5bc660ddc8fa
Create Date: 2020-10-15 18:58:36.869298

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e5f90cb63967"
down_revision = "5bc660ddc8fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("dob", sa.Date(), nullable=True))
    op.add_column("user", sa.Column("gender", sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "gender")
    op.drop_column("user", "dob")
    # ### end Alembic commands ###
