# Generated by Django 3.1.2 on 2020-10-17 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
        ("volunteer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="volunteer",
            old_name="skill",
            new_name="skills",
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="interested_fields",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="VolunteerRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now=True)),
                ("was_present", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="volunteer.volunteer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="volunteer",
            name="events",
            field=models.ManyToManyField(
                through="volunteer.VolunteerRegistration", to="event.Event"
            ),
        ),
    ]
