# Generated by Django 3.1.2 on 2020-10-17 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("volunteer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="end_date_time",
            field=models.DateTimeField(verbose_name="End Date Time"),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="id",
            field=models.OneToOneField(
                db_column="id",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="interested_fields",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Interested Fields"
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="start_date_time",
            field=models.DateTimeField(verbose_name="Start Date Time"),
        ),
    ]
