# Generated by Django 3.1.2 on 2020-10-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "countries"},
        ),
        migrations.AlterModelOptions(
            name="municipality",
            options={"verbose_name_plural": "municipalities"},
        ),
    ]
