# Generated by Django 3.1.2 on 2020-11-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_auto_20201017_2250"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="is_rural",
            field=models.BooleanField(default=False),
        ),
    ]
