# Generated by Django 3.1.3 on 2020-11-07 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_municipality_is_rural"),
        ("user", "0002_auto_20201017_2121"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="dob",
            field=models.DateField(verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Middle Name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="permanent_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="perm_user",
                to="address.ward",
                verbose_name="Permanent Address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.BigIntegerField(verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="user",
            name="temporary_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="temp_user",
                to="address.ward",
                verbose_name="Temporary Address",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(phone_number__gte=100), name="phone_number_gte_100"
            ),
        ),
    ]
