# Generated by Django 3.1.3 on 2020-11-07 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_auto_20201107_2332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.BigIntegerField(
                validators=[django.core.validators.MinValueValidator(100)],
                verbose_name="Phone Number",
            ),
        ),
    ]
