# Generated by Django 3.1.3 on 2020-11-08 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_auto_20201108_0004"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.PositiveBigIntegerField(
                validators=[django.core.validators.MinValueValidator(100)],
                verbose_name="Phone Number",
            ),
        ),
    ]
