# Generated by Django 3.1.3 on 2020-11-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_auto_20201108_1137"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="phone_number_gte_100",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(phone_number__gte=100), name="user_phone_number_gte_100"
            ),
        ),
    ]
