# Generated by Django 3.1.3 on 2020-12-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_merge_20201108_1443"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(gender__in=("M", "F", "L", "G", "B", "T", "N")),
                name="user_gender_in_valid_choices",
            ),
        ),
    ]
