# Generated by Django 3.1.3 on 2020-12-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_auto_20201205_1607"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="user_gender_in_valid_choices",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(gender__in=("M", "F", "L", "G", "B", "T", "N")),
                name="user_gender_in_valid_choices",
            ),
        ),
    ]
