# Generated by Django 3.1.4 on 2020-12-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_auto_20201205_1622"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="user_gender_in_valid_choices",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(gender__in=("M", "F", "L", "G", "B", "T", "N")),
                name="user_gender_in_valid_choices",
            ),
        ),
    ]
