# Generated by Django 3.1.4 on 2020-12-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_auto_20201216_1818"),
        ("user", "0017_auto_20201216_1754"),
    ]

    operations = []
